# Site settings
title: Hi, I'm Michael.
description: Michael Velazquez' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Velazquez
user_title:
user_job_title: Data Analyst
email: MichaelVSchool@gmail.com
github_username:  Exagged

exclude: ['package.json', 'src' , 'node_modules']
